// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1JqyUEJ9S6rqX1XEKn_IsKhAcvanepcE',
    appId: '1:1056792883157:web:65ebcc1774658de906d75c',
    messagingSenderId: '1056792883157',
    projectId: 'judo-club-2a7b3',
    authDomain: 'judo-club-2a7b3.firebaseapp.com',
    storageBucket: 'judo-club-2a7b3.firebasestorage.app',
    measurementId: 'G-D5S2E5PKTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvMj8C6Dw5Kcm3JhITfr599eyeThEc5o0',
    appId: '1:1056792883157:android:d3c9a29a97b56ca906d75c',
    messagingSenderId: '1056792883157',
    projectId: 'judo-club-2a7b3',
    storageBucket: 'judo-club-2a7b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvfz8x3Jr73R5fbNPTNkLpPs59E1KG8Q8',
    appId: '1:1056792883157:ios:953429c9bd40442a06d75c',
    messagingSenderId: '1056792883157',
    projectId: 'judo-club-2a7b3',
    storageBucket: 'judo-club-2a7b3.firebasestorage.app',
    iosBundleId: 'com.judoclub.judoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvfz8x3Jr73R5fbNPTNkLpPs59E1KG8Q8',
    appId: '1:1056792883157:ios:953429c9bd40442a06d75c',
    messagingSenderId: '1056792883157',
    projectId: 'judo-club-2a7b3',
    storageBucket: 'judo-club-2a7b3.firebasestorage.app',
    iosBundleId: 'com.judoclub.judoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1JqyUEJ9S6rqX1XEKn_IsKhAcvanepcE',
    appId: '1:1056792883157:web:c87288eb27be542f06d75c',
    messagingSenderId: '1056792883157',
    projectId: 'judo-club-2a7b3',
    authDomain: 'judo-club-2a7b3.firebaseapp.com',
    storageBucket: 'judo-club-2a7b3.firebasestorage.app',
    measurementId: 'G-BJF0DTR9KH',
  );
}
